# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  Config: 'Debug'


trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:


- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: '$(Config)'
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*UnitTests*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: false
    otherConsoleOptions: '/framework:NETCoreApp,Version=v2.1'


